package ru.redbyte.redbytefx

internal const val RB_INPUT_UNIFORM = "uContent"
internal const val RB_RESOLUTION_UNIFORM = "uResolution"

internal val RESERVED_USER_FUNCTION_NAMES: Set<String> = setOf(
    "abs",
    "atan",
    "bool",
    "bool2",
    "bool3",
    "bool4",
    "break",
    "case",
    "ceil",
    "clamp",
    "const",
    "continue",
    "cos",
    "default",
    "do",
    "dot",
    "else",
    "false",
    "float",
    "float2",
    "float3",
    "float4",
    "floor",
    "for",
    "fract",
    "half",
    "half2",
    "half3",
    "half4",
    "if",
    "in",
    "inout",
    "int",
    "int2",
    "int3",
    "int4",
    "layout",
    "length",
    "main",
    "max",
    "min",
    "mix",
    "mod",
    "out",
    "pow",
    "radians",
    "return",
    "shader",
    "sin",
    "smoothstep",
    "step",
    "switch",
    "true",
    "uniform",
    "void",
    "while"
)
